### ISSUE TITLE
Twilio.Mvc references System.Web.Mvc 2.0.0.0

### ISSUE THREAD

**Issue by alexcchan** [twilio/twilio-csharp#116]
The project “Twilio.Mvc” is hard referencing System.Web.Mvc Version 2.0.0.0. Can you please edit the project and disable the hard reference and update the Nuget packages. This should be as easy as setting the “Specific Version” property to false within the projects references list for System.Web.Mvc. This hard reference is causing issues when deploying to Azure web roles.

ref: 189341

**Comment by mplacona** [comment]
Good point. Do you wanna make the change and send us a PR? Just please make sure the tests run first.

**Comment by devinrader** [comment]
Just fixed this.  The fix and its reprocussions are a bit more complex that simpy changing the specific version.  To support using newer MVC versions as the dependency means dropping support for MVC 2  and changing the project to build against .NET 4.0 instead of .NET 3.5.  This was fixed in package version 3.1.14.
