### ISSUE TITLE
'Total' property is removed from class 'TwilioListBase'!!!

### ISSUE THREAD

**Issue by menocomp** [twilio/twilio-csharp#172]
I did update to version 4 and the 'total' property under this class 'TwilioListBase' is removed with no reason although it is represented in the rest calls. 
In this changeset https://github.com/twilio/twilio-csharp/commit/41fa22183a97f610875bc15edf019baac678077e 

Would you please add it again? also can we have all classes as partial? that would make it easy for developers to extend the classes functionlity.

**Comment by devinrader** [comment]
Hey @menocomp, thanks for using Twilio. Those properties were removed from the helper library because they will be removed from the API by the nend of August:

https://www.twilio.com/engineering/2015/04/16/replacing-absolute-paging-with-relative-paging

re: partial classes, are there specific classes you think would benefit from this?

**Comment by msameer** [comment]
If it's still in Twilio API it should be annotated as [Obsolete] till they actually remove it.
Removing it right away like this forces us to change our code at once without a heads-up.

**Comment by skimbrel** [comment]
@msameer The Twilio helper libraries follow semantic versioning as described at http://semver.org. In keeping with this, we made a major version bump to this library when we removed the absolute paging properties. The release notes in this repository and on nuget.org stated as much; if you still need the old properties you should be able to pin your dependency until you're ready to upgrade.
