### ISSUE TITLE
How to maintain session in twilio

### ISSUE THREAD

**Issue by kunalrai** [twilio/twilio-csharp#186]
Dear team,
How to maintain session in twilio for example when I refresh the page it does not terminate my call session. I have to maintain my agent state on page refresh

**Comment by devinrader** [comment]
It sounds like maybe you are using Twilio Client?  If I am right, then because Twilio Client is a JavaScript library, if you reload the web page that is running the JavaScript, then there isn't a way to keep the call going.  The browser stops running the JavaScript once its starts to refresh the page and reloads the entire JS library.  

If you want to refresh part of a webpage while keeping a Twilio Client call open you can look at using something like AJAX to make server requests from the loaded page asynchronously, or use frames to load more than one page in the same browser window.

Hope that helps.
