### ISSUE TITLE
Unable to use a library in projects with strong name (assembly sign)

### ISSUE THREAD

**Issue by dsosunov** [twilio/twilio-csharp#298]
The Team,
Please add strong name for all assemblies before publish to public NuGet repository.

Thanks.

P.S. As workaround we are using ildasm/ilasm to resign assembly and use our internal repository.
But it adds additional work to update versions.

**Comment by jingming** [comment]
https://github.com/twilio/twilio-csharp/pull/334

**Comment by brutaldev** [comment]
Shamelss plug: https://github.com/brutaldev/StrongNameSigner

**Comment by dprothero** [comment]
There seems to be a lot of disagreement over whether strong naming assemblies for open source projects is a good idea or not. A few examples:
https://github.com/libgit2/libgit2sharp/issues/212
https://github.com/ericsink/SQLitePCL.raw/issues/53

It would seem caution is warranted, particularly if this isn't something commonly needed _and_ there are viable workarounds (thanks for the StrongNameSigner link @brutaldev - that looks perfect)

Would love to hear some input from the community on this.

**Comment by brutaldev** [comment]
The very reason that tool was created was because of the [discussion of strong naming that started on NuGet](http://nuget.codeplex.com/discussions/247827) about whether strong naming had any future and I had requirements to keep them despite major libraries removing their strong names. Some big players decided to drop strong naming while others support both in NuGet.

A good example of a popular package supporting both is StackExchange.Redis
With strong name: [StackExchange.Redis.StrongName](https://www.nuget.org/packages/StackExchange.Redis.StrongName/) (1 million downloads)
Without strong name: [StackExchange.Redis](https://www.nuget.org/packages/StackExchange.Redis/) (1.7 million downloads)

From these numbers I would say strong naming is not quite out of the race yet, enough people are still required to use it for whatever reason which makes tools such as mine still relevant and useful many years later.

**Comment by jmctwilio** [comment]
Closing this issue as no action will be taken for now beyond the work around noted above.

**Comment by dprothero** [comment]
Leaving this here for others who come across this page:
https://support.twilio.com/hc/en-us/articles/360008375953-Does-Twilio-provide-a-strong-named-assembly-of-the-C-helper-library-
