### ISSUE TITLE
Undocumented breaking change (CallResource.Price)

### ISSUE THREAD

**Issue by tuhland** [twilio/twilio-csharp#505]
For some reason the latest release changed the CallResource.Price data type from decimal to string.
This was not documented in the release notes (and thus not marked as breaking).

This happened in e748ab4df42b401ff20d67cda1519c2b72df92e8

**Comment by childish-sambino** [comment]
Yeah, depending on the type of change to the upstream API definition there may not be a changelog entry indicating what changed. Looking into switching this logic so that _all_ changes would require an entry in the release notes. Note that this might bloat the release notes and would not necessarily ensure breaking changes get marked as **breaking** and roll the MINOR version.

**Comment by childish-sambino** [comment]
This logic was rolled out recently so all changes to the upstream API definition require a matching changelog entry.
