### ISSUE TITLE
Twilio.Rest.Bulkexports.V1.Export.DayResource.FetchAsync throws exception

### ISSUE THREAD

**Issue by jweiss3034** [twilio/twilio-csharp#534]
### Issue Summary
When using the Twilio.Rest.Bulkexports.V1.Export.DayResource.Fetch or Twilio.Rest.Bulkexports.V1.Export.DayResource.FetchAsync methods to obtain an exported day for the "Messages" path a Twilio.Exceptions.APIException with an inner exception of JsonReaderException is thrown.  I assume this is due to the response actually being a gzip compressed file rather than a S3 link as per the documentation.  I was able to work around this using my own HTTPClient call that performed a response.content.ReadAsByteArrayAsync() and then save the file.

### Code Snippet
```csharp
TwilioClient.Init("accountSid", "authToken");

var days = await DayResource.ReadAsync(pathResourceType: "Messages");

foreach (var dayResource in days)
{
    var day = await DayResource.FetchAsync(pathResourceType: "Messages", dayResource.Day);
    Console.WriteLine(day.FriendlyName);
}

```

### Exception/Log
```
Twilio.Exceptions.ApiException
  HResult=0x80131500
  Message=Unexpected character encountered while parsing value: . Path '', line 0, position 0.
  Source=Twilio
  StackTrace:
   at Twilio.Rest.Bulkexports.V1.Export.DayResource.FromJson(String json)
   at Twilio.Rest.Bulkexports.V1.Export.DayResource.<FetchAsync>d__2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Twilio.Rest.Bulkexports.V1.Export.DayResource.<FetchAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DownloadTwilioBulkExports.Program.<Main>d__1.MoveNext() in C:\Users\jweiss\source\repos\DownloadTwilioBulkExports\DownloadTwilioBulkExports\Program.cs:line 33

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
JsonReaderException: Unexpected character encountered while parsing value: . Path '', line 0, position 0.

```

### Technical details:
* twilio-csharp version: 5.45.2
* csharp version: dotnet Core 3.1

**Comment by thinkingserious** [comment]
Hello @jweiss3034,

Thank you for reporting this issue!

I am having trouble reproducing this issue, here are are few follow up questions:

1. Is the line of code that triggers the exception? `var day = await DayResource.FetchAsync(pathResourceType: "Messages", dayResource.Day);`
2. If 1. is true, do any of the statements execute in the loop or does it fail on the first iteration?

Thanks!

With best regards,

Elmer

**Comment by jweiss3034** [comment]
Elmer,

I apologize for not being more clear.  

1. Yes, that is the line that is throwing the exception for me.
2. Yes, It fails on the first iteration

I have also tried updating to the latest version of Newtonsoft.Json (12.0.3) with no change.

Please let me know if I can provide any further information.

**Comment by childish-sambino** [comment]
Relates to https://github.com/twilio/twilio-cli/issues/207

Pretty sure what's going on here is the Twilio API is responding with a redirect response code to an S3 URL which the client then automatically follows (since this is the default behavior, [here's](https://stackoverflow.com/a/10647245/1660457) an example of how to change it). The library then attempts to JSON-parse the file payload which then fails.

What we do in other libraries (and which I feel is needed here) is to _not_ follow redirects and just expect/allow `3XX` response codes. So then your client code will get the _proper_ response which includes the S3 URL and can be JSON-parsed.

Places where the default clients are instantiated:
* https://github.com/twilio/twilio-csharp/blob/9a578fc1a0685a5f4d8789c3b9c3a14cbfc7cf43/src/Twilio/Http/SystemNetHttpClient.cs#L30
* https://github.com/twilio/twilio-csharp/blob/9a578fc1a0685a5f4d8789c3b9c3a14cbfc7cf43/src/Twilio/Http/Net35/WebRequestClient.cs#L17

And where we inspect the response code: https://github.com/twilio/twilio-csharp/blob/9a578fc1a0685a5f4d8789c3b9c3a14cbfc7cf43/src/Twilio/Clients/TwilioRestClient.cs#L149

This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.
