### ISSUE TITLE
Differentiate between resource not being found and API connection issue

### ISSUE THREAD

**Issue by LiamMoorcroft** [twilio/twilio-csharp#548]
### Issue Summary
When using the lookup endpoint in two situations, the first being when a resource can not be found for a given phone number or the second being when the URI  can not be found (due to server being down) they will both be treated as a Twilio API exception using the same code (20404) and status (404) from my understanding it is impossible to differentiate between the two.

```ApiConnectionException``` is an option but I am unsure if an empty response will always be returned for a failure to connect to the API.

What I am looking for is a mechanism to identify when a phone number is invalid and when the URI can not be found.

### Steps to Reproduce
1. Using the v1 phone number lookup endpoint
2. Supply an invalid phone number and inspect that a 404 response is returned

### Code Snippet
```csharp
try
{
    var twilioResponse = await _twilioClient.FetchAsync(phoneNumber, countryCode);
}
    catch (Twilio.Exceptions.ApiException e)
{
    // when a phone number can not be looked up or the URI can not be found both will end up here
}
```

### Technical details:
* twilio-csharp version: 5.41.1
* csharp version: .NET Core 3.1

**Comment by thinkingserious** [comment]
Hello @LiamMoorcroft,

[Here is the documentation](https://www.twilio.com/docs/lookup/api?code-sample=code-carrier-lookup-with-e164-formatted-number&code-language=C%23&code-sdk-version=5.x) for executing a lookup in this helper library. I'm not quite sure what `await _twilioClient.FetchAsync(phoneNumber, countryCode);` is meant to do, but it does appear that when using the example linked code, we would not return an exception.

Could you please provide the relevant missing bits of the code that is causing this error so that we may reproduce? 

Thank you!

With best regards,

Elmer

**Comment by LiamMoorcroft** [comment]
Hi Elmer,

Apologies for the lateness in my reply.

I'm not surprised my code snippet was confusing to you seeing as I have shown you my abstraction of the twilio functionality, so apologies for that.

Having looked into this further, I do not believe this is an issue and more a misunderstanding on my end.

Have a great weekend.

Thanks,

Liam
