### ISSUE TITLE
Release notes? Upgrades? Changes?  Out of date documentation

### ISSUE THREAD

**Issue by DonThompson** [twilio/twilio-csharp#553]
Your Upgrades.md (in the root) states:
https://github.com/twilio/twilio-csharp/blob/main/UPGRADE.md

"After 5.0.0 all MINOR and MAJOR version bumps will have upgrade notes posted here."

However, this file has not been updated since 2017.  Looks like maybe changes.md has taken over?
https://github.com/twilio/twilio-csharp/blob/main/CHANGES.md

Maybe these should be combined?

**Comment by JenniferMah** [comment]
Hi @DonThompson,
We use the Upgrades.md to help document the changes for major version rolls of the library while the Changes.md is used to document changes to the library itself. Since these serve two different purposes we will continue to keep these seprated. You are correct that `"After 5.0.0 all MINOR and MAJOR version bumps will have upgrade notes posted here."` is an inaccurate message. I will go ahead and submit a [PR](https://github.com/twilio/twilio-csharp/pull/554) to clarify what the upgrade guide should document to clear up any confusion.
