### ISSUE TITLE
Twilio Voice API Async Support

### ISSUE THREAD

**Issue by mfuzailzubari** [twilio/twilio-csharp#590]
### Issue Summary
In my application of ASP.NET core, I am using mediator pattern which requires Async/Await i.e. Async. I want to integrate my voice API on the same mechanism in which whenever I receive a call on API it will transfer it to suitable handler and then the handler returns the VoiceResponse. 

### Code Snippet
![image](https://user-images.githubusercontent.com/4161179/146925285-85d70492-efb4-435a-b004-26eae37356af.png)

**Comment by eshanholtz** [comment]
Hi @mfuzailzubari 

The `twilio-csharp` helper library supports Async functionality via the `<Action>Async` versions of our functions. For example, if you wanted to create a `CallResource` async, [you would use the `CallResource.CreateAsync()` function](https://www.twilio.com/docs/libraries/reference/twilio-csharp/5.69.0/class_twilio_1_1_rest_1_1_api_1_1_v2010_1_1_account_1_1_call_resource.html#a522c189caebe2c4eeaa4b4c65b1a1fed) instead of `CallResource.Create()`.

**Comment by eshanholtz** [comment]
Closing due to lack of customer response.
